services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - label_studio_data:/label-studio/data
    command: label-studio start --log-level INFO
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  label_studio_data:
