services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./mydata:/label-studio/data
    command: label-studio
    stdin_open: true
    tty: true
    restart: unless-stopped
